### ISSUE TITLE
Installation on gentoo

### ISSUE THREAD

**Issue by GuillaumeSeren** [pyroscope/rtorrent-ps#28]
Hey there,
I was told about this project, and as the ui looks really good and your based on rtorrent,
I would like to install it on gentoo, but I did not find any ebuild available, so if you have any pointers to help installing on this system, that could be great.

An other question, I see in the source, your building process is made by the 'build.sh' shell script,
but inside it, in the build steps you finally call make, why do not just use a plain Makefile (it could be simpler to port it on *any* system) ?

Guillaume :neckbeard:

**Comment by pyroscope** [comment]
Because bash is just as portable as makefiles, especially when they contain… shell commands. Make is for optimizing dependencies, and there are none here.

The build is as it is, and I only directly care for Debian. Anything else must come from people running other stuff.

Use "build.sh install" for an /opt install (which is explained in the readme).

**Comment by GuillaumeSeren** [comment]
Hey @pyroscope 
thank you for quick-reply.

> Because bash is just as portable as makefiles, especially when they contain… shell commands. Make is for optimizing dependencies, and there are none here.
I understand you POV, that's just Makefile are a standard for building project and shell script not (despite my love for shell script), plus using a more 'standard' way to build your project can really help to distribute it across distros, and give you more users.

> The build is as it is, and I only directly care for Debian. Anything else must come from people running other stuff.
Reading the build.sh script I understand you made it for debian first, that's why I asked if you are interested in making a Makefile, which you still can call with your script if you want, but it should really help distro packagers.

**Comment by pyroscope** [comment]
I don't see in what way a Makefile help in adoption, especially since rT-PS is not "distro-compatible" by design (rpath-linking fits no normal distro).

For example, if you wanted to make a "real" Debian package of this, you'd have to put the patches into quilt and get rtorrent/libtorrent as orig tarballs. But I care more for working and stable than policy-conforming.

**Comment by GuillaumeSeren** [comment]
@pyroscope 
i understand your point but as a user I think it is not really easy,
to install it that way, except the case you covered the install process is specific.

I am still trying to find the best way to get it on Gentoo, if you have any pointers let me know !

**Comment by WindfallProphet** [comment]
@GuillaumeSeren 
I'm wondering if docker would work. No idea, but it's worth a try!

**Comment by GuillaumeSeren** [comment]
@WindfallProphet Yes but it would be a bit overkill, instead of *just* compiling it.

I understand the point of the author, it would require more work to make it generic.
