### ISSUE TITLE
Make extended canvas more configurable

### ISSUE THREAD

**Issue by pyroscope** [pyroscope/rtorrent-ps#60]
## Tasks
* :white_check_mark: Update all documentation (description of default columns, new commands)

* :white_check_mark: Clean up code

   * deprecate "ui.style.ratio" and "ui.style.progress"
* :white_check_mark:  Catch errors thrown by render methods, show error indicator (e.what()).
* :bulb: Add ``ui.render.cycle = ‹speed›, ‹cmd1›, ‹cmd2›, …`` to rotate through alternate display values

   * driven by a tick value (increased per canvas refresh)
   * `‹speed›` is measured in ticks
   * `ui.tick` and private `ui.tick.bump` command
   * this means `Ctrl-L` can be used to cycle manually (bump tick count artificially in the key binding)

![final canvas](https://raw.githubusercontent.com/pyroscope/rtorrent-ps/master/docs/_static/img/rt-ps-canvas-v2-final.png)

* :white_check_mark: Add a multi-method for column rendering: `ui.column.render`
  * Call those methods, order is determined by keys as usual
  * Keys encode column title + length ``sort:[?]len[coldef]:title``, with optional parts for sacrificial headers (`?`) and colorization
  * Chop rendered contents to the length of the header
* :white_check_mark: Make chopping of columns UTF8-aware!
* :white_check_mark: Start out with one of the new fields in #29 to make @chros73 happy
* :white_check_mark: X-position (column) must be made dynamic in the code (advance by header length)
* :white_check_mark:  Add colouring support (needed for remaining columns)

  * :white_check_mark: New ``ui.color.custom1…9`` commands
  * :white_check_mark: New *private* ``ui.color.*.index`` commands
  * :white_check_mark: New ``ui.canvas_color[.set]`` command
  * :white_check_mark: Static color definitions in column index (``Cidx/len``): ``"180:2C2/2: ↻"``
  * :white_check_mark: Custom colors moved to index 1…9
  * :white_check_mark: System colors – dynamically mapped color index values, starting at index 90

* :x: Existing columns might be factored into commands, to make everything configurable (`d.‹name›.render`)
* :white_check_mark: Move "tagged" to its own column
* :white_check_mark: Add `convert.magnitude` command (used in scrape columns)
* :white_check_mark: Add `string.map=text,{from,to},…` (for throttle names)
* :white_check_mark: Add `event.view.hide/show` multi command, and call them on view changes
  * ``method.set_key = event.view.hide, ~log, ((print, ((ui.current_view)), " → ", ((argument.0))))``

## Example
Custom columns with custom colors (subject to change):
```ini
ui.color.custom1.set = 242
ui.color.custom2.set = 105
ui.color.custom3.set =  51

method.set_key = ui.column.render, "910:4C15/3C21/1: ✇  "
method.set_key = ui.column.render, "910:4C3/3C2/1: ✇  ", \
    ((convert.human_size, ((d.size_bytes)) ))

method.set_key = ui.column.render, "900:4C24/3C21/1: Σ⇈ "
method.insert = _pyro.middot_custom, private|simple, \
    "branch=d.up.total=,ui.canvas_color.set=C24/3C2/1,ui.canvas_color.set=C2/4 ; cat=\"  · \""
method.set_key = ui.column.render, "900:4C24/3C2/1: Σ⇈ ", \
    ((if, ((d.up.total)), \
        ((convert.human_size, ((d.up.total)), (value, 10) )), \
        ((_pyro.middot_custom)) \
    ))
```
![preview](https://i.imgur.com/KYz5nqn.png)

**Comment by chros73** [comment]
> Start out with one of the new fields in #29 to make @chros73 happy

:D Thank You!!!
This feature will be freaking awesome!!!

Btw, I use 2 more columns (I don't plan to add more):
- https://github.com/chros73/rtorrent-ps/issues/17 
  - this one can be also interesting for you (maybe multiple flavours can be implemented)
- https://github.com/chros73/rtorrent-ps/issues/15 
  - this is how I determine whether a torrent is deletable or not
  - there are 3 state of it: [0|1|2] , 2 means it should be deleted first (these downloads has higher priority when delete task runs)

**Comment by chros73** [comment]
A little more about the deletable variable:
- the idea is simple but the result is really powerful
- it allows us to create a proper sweep functionality (as part of the downloading queue manager)
- this property can be set in my setup:
  - via [watch directories](https://github.com/chros73/rtorrent-ps_setup/blob/master/ubuntu-14.04/home/chros73/.rtorrent-config.rc#L89)
  - manually when [moving torrents](https://github.com/chros73/rtorrent-ps_setup/blob/master/ubuntu-14.04/home/chros73/.rtorrent.rc#L160) into different category
  - manually via [keyboard shortcut](https://github.com/chros73/rtorrent-ps_setup/blob/master/ubuntu-14.04/home/chros73/.pyroscope/rtorrent-ps.rc#L251)
  - the first 2 above use the same [helper method](https://github.com/chros73/rtorrent-ps_setup/blob/master/ubuntu-14.04/home/chros73/.rtorrent.rc#L50)

And at last I'll be ready to switch completely to use pyrocore (instead of the file-based setup) if every aspect of this can be handled by it. (I think only the proper sweep functionality is missing from it).

**Comment by pyroscope** [comment]
See https://github.com/pyroscope/pimp-my-box/blob/master/roles/rtorrent-ps/templates/rtorrent/rtorrent.d/05-rt-ps-columns.rc for config.

**Comment by pyroscope** [comment]
Ad-hoc removal of a column:

    rtxmlrpc -i 'method.set_key = ui.column.render, "~100:3:⋉ "'

This opens interesting possibilities of special views (add a column when showing a view, remove it when leaving it). Hmmm, I guess we need `event.view.changed`.

**Comment by chros73** [comment]
I just took a quick look at the config sample: it's really powerful! :)
Here's an idea about it:
- `string.map` is indeed really powerful!
- for throttle and Data-directory column:
  - we can create new commands for them (similar to `string.map`) that will auto-return the required 1 character:
    - [throttle](https://github.com/chros73/rtorrent-ps/blob/master/patches/ui_pyroscope.cc#L563) and add this into it [this](https://github.com/chros73/rtorrent-ps/blob/master/patches/ui_pyroscope.cc#L613)
    - [Data-directory column](https://github.com/chros73/rtorrent-ps/blob/master/patches/ui_pyroscope.cc#L572)

**Comment by chros73** [comment]
Can be this made that if there's no column definitions in config files then a default inbuilt def is used? (as in main.cc of rtorent)

**Comment by pyroscope** [comment]
> built-in defaults
Certainly not a prio when all you need is an import of a default set. Possibly an extra mention in the setup docs, and a reference to the p-m-b default.

**Comment by chros73** [comment]
So, finally I managed to get to this point to play with it (after backporting it): pretty interesting, thanks! :)

**A. Good things** 

_a. built-in defaults_

It's [easy to do](https://github.com/chros73/rtorrent-ps-ch/blob/feature/canvas_customization/patches/ui_pyroscope.cc#L1014) this, just like in [main.cc](https://github.com/rakshasa/rtorrent/blob/master/src/main.cc#L249) in rtorrent.
(Note that I modded the `uploaded data` column a bit, added `Unsafe data` and `Number of connected peers`, and I haven't included the `throttle` column (I use my own).)

Custom columns defined in this way still can be:
- disabled via config: `method.set_key = ui.column.render, "100:1:☢ "`
- overridden via config: `method.set_key = ui.column.render, "900:6:   ⊼  ", ((convert.human_size, ((d.up.total)), (value, 0) ))`

So, it's perfect! :)

_b. toggle custom columns_

An interesting use-case is when a given terminal has a smaller width than usually, so we can toggle custom columns to see the important information (probably it can be done with multi-method but here it is in the old way toggling 2 columns):
```ini
method.insert = ui.columns.extra.state, value|private, 1

method.insert = ui.columns.extra.enable,  simple|private, "\
       method.set_key = ui.column.render, \"100:1:☢ \", ((string.map, ((cat, ((d.is_open)), ((d.is_active)))), {00, \"▪ \"}, {01, \"▪ \"}, {10, \"╍ \"}, {11, \"▹ \"}));\
       method.set_key = ui.column.render, \"120:1:⌘ \", ((if, ((d.ignore_commands)), ((cat, \"◌ \")), ((cat, \"⚒ \"))));\
       ui.columns.extra.state.set=1"
method.insert = ui.columns.extra.disable, simple|private, "\
       method.set_key = ui.column.render, \"100:1:☢ \";\
       method.set_key = ui.column.render, \"120:1:⌘ \";\
       ui.columns.extra.state.set=0"
method.insert = ui.columns.extra.toggle,  simple, "branch=$ui.columns.extra.state=, ui.columns.extra.disable=, ui.columns.extra.enable="

branch=pyro.extended=,"schedule2 = disable_extra_columns,0,0,\"ui.bind_key=download_list,/,ui.columns.extra.toggle=\""
```

**B. Bad things** 

Unfortunately it's still not usable for me in this state (hence I created a branch for it):

_a. order of built-in/custom columns_

Currently there's no way to put a custom column in between 2 built-in ones, isn't it?

Probably this feature would help this: "Existing columns might be factored into commands, to make everything configurable", meaning every column will be custom column. And with the above "built-in defaults" it's not a problem anymore. :)

_b. coloring chars/columns_

Currently coloring is broken:
- somehow we need to keep track which characters in a given column needs to be colorised
  - in this way it won't matter which order the given column resides

**C. Summary**

Amazing job, as always, thanks! :)

**Comment by chros73** [comment]
I finished it, it was a big chunk of work :)
- all the necessary commands have been created ([here](https://github.com/chros73/rtorrent-ps-ch/blob/develop/patches/command_pyroscope.cc#L751) and [here](https://github.com/chros73/rtorrent-ps-ch/blob/develop/patches/ui_pyroscope.cc#L1034))
- all the default columns [can be overridden ](https://github.com/chros73/rtorrent-ps-ch/blob/develop/patches/ui_pyroscope.cc#L1040) now
  - [example](https://github.com/chros73/rtorrent-ps-ch_setup/issues/135) for this
  - [toggling](https://github.com/chros73/rtorrent-ps-ch_setup/issues/136) extra columns
- keeping track which characters in a given column needs to be colorized

Commits: https://github.com/chros73/rtorrent-ps-ch/issues/119

**A. Coloring columns**

_a. Theory_

That was the tricky part. Initially I wanted to modify the `render_columns` method to do coloring there but I realized that later they will be overridden.

So the idea is to track all the positions of all the columns all the time in [render_columns](https://github.com/chros73/rtorrent-ps-ch/blob/develop/patches/ui_pyroscope.cc#L526) using a simple [map](https://github.com/chros73/rtorrent-ps-ch/blob/develop/patches/ui_pyroscope.cc#L132) for this:
- we use the label of the columns (from the column definition) as key in the map, e.g. `☢`
  - they are unique anyway, since we have the in-built default columns
- after that we just [check](https://github.com/chros73/rtorrent-ps-ch/blob/develop/patches/ui_pyroscope.cc#L623) whether the given label is available (column is visible)
- we have to [empty](https://github.com/chros73/rtorrent-ps-ch/blob/develop/patches/ui_pyroscope.cc#L563) this map all the time: columns can be removed on the fly

_b. Limitations_
- user created custom columns can't be colorized
- funky coloring effects can happen if a user overrides a colored column

I'll write more (if I'll have time) about what I did and why, but in the meantime you can go through all the commits if you're interested (they are on `develop` branch for now, although I considered this feature as finished).

This feature is simply amazing, I'd never have thought of this: Thank You! :)

**Comment by chros73** [comment]
Can you take a look at the name of commands the I gave them, whether you like it or not?
- [here](https://github.com/chros73/rtorrent-ps-ch/blob/develop/patches/command_pyroscope.cc#L751) and [this](https://github.com/chros73/rtorrent-ps-ch/blob/develop/patches/command_pyroscope.cc#L755)
- and [here](https://github.com/chros73/rtorrent-ps-ch/blob/develop/patches/ui_pyroscope.cc#L1034)
  - I couldn't come up better names for them (that is short and descriptive)

**Comment by chros73** [comment]
**C. Replacing couple of glyphs**

I had to (!) replace these glyphs `⚡ ⌚` with these ones `⋮ ⌬` on my setup.

That's actually a concerning issue.
I upgraded ([compiled](https://github.com/chros73/build-tmux)) tmux to v2.6 on the same setup about half a year ago (still Ubuntu 14.04, nothing else has been changed), and I realised at that time that column labels were off, and they definitely worked fine with v1.8.

Searching for similar issues, I found e.g. these: [utf8 Rendering Issue](https://github.com/tmux/tmux/issues/515), [multibyte characters](https://github.com/tmux/tmux/issues/805)
I didn't have time to track down which is the last tmux version that works fine, if I'll will then I'll make an issue about it there.

The point is that with the wrong reported width, label rendering was off.
Since this issue doesn't relate to the actual chars, that means any user can experience such rendering problems with any (?) multibyte chars and we can't really do much about it, only telling them to change those and recompile the client.

**D. Other small changes**

_a. column rendering changes_
- header text is also [chopped](https://github.com/chros73/rtorrent-ps-ch/blob/develop/patches/ui_pyroscope.cc#L523) by the length defined in the header
  - user can enter more chars than the specified length otherwise and it'd cause wrong label rendering
- column [labels and their values](https://github.com/chros73/rtorrent-ps-ch/blob/develop/patches/ui_pyroscope.cc#L1044) are updated to the proper length

_b. fixing rendering issue with name column_
- if the width of the canvas (terminal) was smaller then the width of defined columns then the name of download overwrote all the other info in the same line
  - [this fixes](https://github.com/chros73/rtorrent-ps-ch/blob/develop/patches/ui_pyroscope.cc#L613) it

**Comment by chros73** [comment]
I added section D.d. above. This was the last change I wanted to make.

So, what do you think about the name of the above new commands in section B.?
Do I have to change them, or is it good with you? It's up to You entirely, let me know what you think :)

**Comment by pyroscope** [comment]
Example for custom column with custom colors (subject to change):
```ini
method.insert = _pyro.middot_custom1, simple, "ui.canvas_color.set=22 ; cat=\"  · \""
method.set_key = ui.column.render, "900:4: Σ⇈ ",\
    ((if, ((d.up.total)), \
        ((convert.human_size, ((d.up.total)), (value, 10))), \
        ((_pyro.middot_custom1)) \
    ))
```

**Comment by pyroscope** [comment]
Look at the code, all this is already 80% solved.

**Comment by chros73** [comment]
> giving up on dynamic colors for now

No worries at all. It's not really important for me:
- I like the idea of theming (although noone else seems to really care about it, apart from us :) ), and if it's not implemented properly then theming will be screwed (maybe I'll take a look how [these 4 season](https://mooffie.github.io/mc-skins-16Mcolors/) ones look with ps :) )
- too much color can be too much :) , although I like the scraping/peers color change (maybe the 2 yellow could be swapped)

Later we can get back to it if we feel the need for it, but:
- I have been thinking about what other columns we would need (by looking at other clients) and I couldn't come up any of them :) , it's really informative as it is now
  - only a "remaining time/last xfer" column popped in my mind but Only when something is being leeched, but I'm not sure about this one either, so I haven't done it in my setup project (could be dynamically visible/hidden)
  - the only reason is why I think custom columns is great because the terminal size can be small sometimes (e.g. with mobile devices in portrait mode), so visibility of non critical columns [can be toggled](https://github.com/chros73/rtorrent-ps-ch_setup/blob/e199fe818d5c253da47197db0ae2833a4a8a9f88/ubuntu-14.04/home/chros73/.pyroscope/rtorrent-ps.rc#L386)

So built-in colorizing isn't a problem, at least that's what I think.

You can go through/grab what I did (do a diff), along the [documentation](https://github.com/chros73/rtorrent-ps-ch/blob/master/docs/Manual.rst#uicolumnrender), and make a release, it's well worth it. :)

> Maybe you can find out what's wrong.

If You, The Master couldn't then it's a slight chance that I can. :) Anyway I'll take a look when I'll have time and I'll be in the mood for it. Create a branch for it for reference, please.

And as I said earlier, thanks for the brilliant idea and the clever, clean implementation, I'd have never thought of this by myself!

**Comment by pyroscope** [comment]
Done-done now with the canvas config, time display is "up rate / leech time", and "down rate / completion or loaded time" (with "leech = completed - loaded").

**Comment by pyroscope** [comment]
With the upcoming change, minimum usable terminal size is 40×15 (usable = no strange overlaps).
