### ISSUE TITLE
PS-1.1 release

### ISSUE THREAD

**Issue by pyroscope** [pyroscope/rtorrent-ps#92]
* Finish `CHANGES.md`
* Tag the release, put changelog up on GitHub, bump version
* Release final version on Bintray (see below on `bintray.sh`)
* Make a stable / 1.1. snapshot of docs
* Bump version in `docs/conf.py`
* Announce

**Comment by chros73** [comment]
> Release final version on Bintray

I modified the [bintray.sh](https://github.com/chros73/rtorrent-ps-ch/blob/ffdea0254942007e6143be4c71b2030da76631d0/bintray.sh#L19) script to publish (`;publish=1` in upload URL) and [display packages in download list](https://github.com/chros73/rtorrent-ps-ch/blob/ffdea0254942007e6143be4c71b2030da76631d0/bintray.sh#L31).
(I even had to mod the upload part (`;deb_*` params), maybe because I set Debian distrib in Bintray?)

**Comment by pyroscope** [comment]
https://www.reddit.com/r/torrents/comments/8v9hs7/release_of_rtorrentps_v11_20180701/
